"""Generate src/i18n/i18n_data.c from the translation tables and the
Fusion Pixel Font (8px, OFL-1.1).

    python tools/i18n/gen_i18n.py            (run from the project root)

Inputs
  tools/i18n/*.tsv   rows: english<TAB>zh-Hans<TAB>zh-Hant<TAB>ja<TAB>ko
                     ('//' starts a comment line; empty cells fall back to English)
  .tools/fonts/fusion-pixel-8px-monospaced-{zh_hans,zh_hant,ja,ko}.bdf

Checks (the build stops on any of them)
  - printf conversions (%d, %s, %.0f ...) and '#' value markers must appear
    in the same order in every translation, so formats can never crash;
  - every glyph used by a language must exist in that language's font.
Only the glyphs the translations use are embedded (a few KB per language).
"""
import glob
import os
import re
import sys

LANGS = ['zh_hans', 'zh_hant', 'ja', 'ko']
FONT_DIR = '.tools/fonts'
OUT = 'src/i18n/i18n_data.c'
SPEC = re.compile(r'%(?:%|0?\d*(?:\.\d+)?[dsfuxc])')
LANG_NAMES = ['简体中文', '繁體中文', '日本語', '한국어']


def load_rows():
    rows = {}
    for path in sorted(glob.glob('tools/i18n/*.tsv')):
        for n, line in enumerate(open(path, encoding='utf-8'), 1):
            line = line.rstrip('\n').rstrip('\r')
            if not line.strip() or line.startswith('//'):
                continue
            cells = line.split('\t')
            if len(cells) != 5:
                sys.exit(f'{path}:{n}: expected 5 columns, got {len(cells)}')
            en = cells[0]
            if en in rows and rows[en] != cells[1:]:
                sys.exit(f'{path}:{n}: "{en}" translated twice differently')
            rows[en] = cells[1:]
    return rows


def check_formats(rows):
    bad = 0
    for en, trs in rows.items():
        want = SPEC.findall(en), en.count('#')
        for lang, t in zip(LANGS, trs):
            if t and (SPEC.findall(t), t.count('#')) != want:
                print(f'format mismatch [{lang}] {en!r} -> {t!r}')
                bad += 1
    if bad:
        sys.exit(f'{bad} format mismatches')


def parse_bdf(path, wanted):
    """Return {codepoint: [8 row bytes]} for the wanted code points."""
    glyphs, ascent = {}, 7
    cp, bbx, rows, in_bitmap = None, None, [], False
    for line in open(path, encoding='utf-8', errors='replace'):
        parts = line.split()
        if not parts:
            continue
        key = parts[0]
        if key == 'FONT_ASCENT':
            ascent = int(parts[1])
        elif key == 'ENCODING':
            cp = int(parts[1])
        elif key == 'BBX':
            bbx = [int(v) for v in parts[1:5]]
        elif key == 'BITMAP':
            in_bitmap, rows = True, []
        elif key == 'ENDCHAR':
            if cp in wanted:
                glyphs[cp] = to_cell(bbx, rows, ascent)
            in_bitmap = False
        elif in_bitmap:
            rows.append(int(key, 16))
    return glyphs


def to_cell(bbx, rows, ascent):
    w, h, xoff, yoff = bbx
    cell = [0] * 8
    nbits = ((w + 7) // 8) * 8
    top = ascent - (yoff + h)
    for i, bits in enumerate(rows):
        y = top + i
        if not 0 <= y < 8:
            continue
        for c in range(w):
            if bits & (1 << (nbits - 1 - c)) and 0 <= xoff + c < 8:
                cell[y] |= 0x80 >> (xoff + c)
    return cell


def c_string(s):
    out = []
    for b in s.encode('utf-8'):
        if b in (0x22, 0x5C):
            out.append('\\' + chr(b))
        elif 32 <= b < 127:
            out.append(chr(b))
        else:
            out.append('\\%03o' % b)          # octal: never swallows the next char
    return '"' + ''.join(out) + '"'


def main():
    rows = load_rows()
    check_formats(rows)
    lines = ['/* GENERATED by tools/i18n/gen_i18n.py - do not edit by hand.',
             ' * CJK glyphs: Fusion Pixel Font 8px (c) TakWolf and contributors,',
             ' * SIL Open Font License 1.1 - see assets/fonts/. */',
             '#include "i18n.h"', '', 'const I18nEntry i18n_strings[] = {']
    for en in sorted(rows):
        trs = ', '.join(c_string(t) for t in rows[en])
        lines.append(f'    {{ {c_string(en)}, {{ {trs} }} }},')
    lines += ['};', f'const int i18n_count = {len(rows)};', '']
    counts = []
    for li, lang in enumerate(LANGS):
        text = ''.join(r[li] for r in rows.values()) + LANG_NAMES[li]
        wanted = {ord(ch) for ch in text if ord(ch) >= 0x80}
        glyphs = parse_bdf(os.path.join(FONT_DIR, f'fusion-pixel-8px-monospaced-{lang}.bdf'), wanted)
        missing = sorted(wanted - set(glyphs))
        if missing:
            sys.exit(f'{lang}: no glyph for ' + ''.join(chr(c) for c in missing))
        lines.append(f'static const CjkGlyph glyphs_{lang}[] = {{')
        for cp in sorted(glyphs):
            lines.append('    { 0x%04X, { %s } },' % (cp, ', '.join('0x%02X' % b for b in glyphs[cp])))
        lines += ['};', '']
        counts.append(len(glyphs))
    lines.append('const CjkGlyph *const i18n_glyphs[LANG_COUNT] = { NULL, '
                 + ', '.join(f'glyphs_{l}' for l in LANGS) + ' };')
    lines.append('const int i18n_glyph_count[LANG_COUNT] = { 0, ' + ', '.join(map(str, counts)) + ' };')
    open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
    print(f'{len(rows)} strings; glyphs ' + ', '.join(f'{l} {n}' for l, n in zip(LANGS, counts)))


if __name__ == '__main__':
    main()
